ATHENA_REGION_NAME: us-east-1
ATHENA_WORK_GROUP: primary
ATHENA_SCHEMA_NAME: default
ATHENA_CATALOG_NAME: AwsDataCatalog
ATHENA_S3_STAGING_DIR: ""
ATHENA_CUSTOMERS_TABLE: customers
ATHENA_PRODUCTS_TABLE: products
ATHENA_ORDERS_TABLE: orders
MINISTACK_ENDPOINT_URL: http://localhost:4566
MINISTACK_AWS_ACCESS_KEY_ID: test
MINISTACK_AWS_SECRET_ACCESS_KEY: test
MINISTACK_ATHENA_S3_STAGING_DIR: s3://gx-demo-athena-results/
